import { UNIFIED_SUBJECT_TOPICS_DATABASE } from '../../data/subjectTopicsData';
import { SubjectItem, PaperNode, PresetExamConfig } from './types';

export const EXAM_SUBJECTS: SubjectItem[] = [
  {
    key: 'bangla',
    name: 'বাংলা',
    nameEnglish: 'Bangla',
    category: 'general',
    iconType: 'bangla',
    color: '#DC2626',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-100',
    totalQuestions: 8100,
    solvedQuestions: 154,
  },
  {
    key: 'english',
    name: 'English',
    nameEnglish: 'English',
    category: 'general',
    iconType: 'english',
    color: '#4338CA',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-100',
    totalQuestions: 7500,
    solvedQuestions: 210,
  },
  {
    key: 'gk',
    name: 'সাধারণ জ্ঞান',
    nameEnglish: 'General Knowledge',
    category: 'general',
    iconType: 'gk',
    color: '#0284C7',
    bgColor: 'bg-sky-50',
    borderColor: 'border-sky-100',
    totalQuestions: 6200,
    solvedQuestions: 98,
  },
  {
    key: 'statistics',
    name: 'পরিসংখ্যান',
    nameEnglish: 'Statistics',
    category: 'science',
    iconType: 'statistics',
    color: '#0D9488',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-100',
    totalQuestions: 3400,
    solvedQuestions: 45,
  },
  {
    key: 'physics',
    name: 'পদার্থবিজ্ঞান',
    nameEnglish: 'Physics',
    category: 'science',
    iconType: 'physics',
    color: '#16A34A',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-100',
    totalQuestions: 9500,
    solvedQuestions: 320,
  },
  {
    key: 'agriculture',
    name: 'কৃষিশিক্ষা',
    nameEnglish: 'Agriculture',
    category: 'science',
    iconType: 'agriculture',
    color: '#059669',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-100',
    totalQuestions: 4100,
    solvedQuestions: 30,
  },
  {
    key: 'chemistry',
    name: 'রসায়ন',
    nameEnglish: 'Chemistry',
    category: 'science',
    iconType: 'chemistry',
    color: '#EA580C',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-100',
    totalQuestions: 8900,
    solvedQuestions: 154,
  },
  {
    key: 'home_science',
    name: 'গার্হস্থ্য বিজ্ঞান',
    nameEnglish: 'Home Science',
    category: 'general',
    iconType: 'home_science',
    color: '#DB2777',
    bgColor: 'bg-pink-50',
    borderColor: 'border-pink-100',
    totalQuestions: 2800,
    solvedQuestions: 12,
  },
  {
    key: 'biology',
    name: 'জীববিজ্ঞান',
    nameEnglish: 'Biology',
    category: 'science',
    iconType: 'biology',
    color: '#059669',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-100',
    totalQuestions: 8200,
    solvedQuestions: 180,
  },
  {
    key: 'math',
    name: 'উচ্চতর গণিত',
    nameEnglish: 'Higher Math',
    category: 'science',
    iconType: 'math',
    color: '#D97706',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-100',
    totalQuestions: 9100,
    solvedQuestions: 240,
  },
  {
    key: 'psychology',
    name: 'মনোবিজ্ঞান',
    nameEnglish: 'Psychology',
    category: 'general',
    iconType: 'psychology',
    color: '#9333EA',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-100',
    totalQuestions: 3100,
    solvedQuestions: 55,
  },
  {
    key: 'ict',
    name: 'তথ্য ও যোগাযোগ প্রযুক্তি',
    nameEnglish: 'ICT',
    category: 'science',
    iconType: 'ict',
    color: '#C026D3',
    bgColor: 'bg-fuchsia-50',
    borderColor: 'border-fuchsia-100',
    totalQuestions: 5400,
    solvedQuestions: 140,
  },
  {
    key: 'mental_ability',
    name: 'মানসিক দক্ষতা',
    nameEnglish: 'Mental Ability',
    category: 'general',
    iconType: 'mental_ability',
    color: '#2563EB',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-100',
    totalQuestions: 4200,
    solvedQuestions: 80,
  },
  {
    key: 'iba',
    name: 'IBA',
    nameEnglish: 'IBA Admission',
    category: 'business',
    iconType: 'iba',
    color: '#991B1B',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-100',
    totalQuestions: 3900,
    solvedQuestions: 64,
  },
];

export const PRESET_EXAMS_LIST: PresetExamConfig[] = [
  {
    id: 'du_ka',
    name: "ঢাবি 'ক'",
    title: "ঢাবি 'ক' প্রিসেট",
    durationMinutes: 45,
    totalQuestions: 60,
    mandatorySubjects: [
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 15 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 15 },
    ],
    optionalSubjects: [
      { subjectKey: 'bangla', name: 'বাংলা', count: 15 },
      { subjectKey: 'english', name: 'English', count: 15 },
      { subjectKey: 'math', name: 'উচ্চতর গণিত', count: 15 },
      { subjectKey: 'biology', name: 'জীববিজ্ঞান', count: 15 },
    ],
    requiredOptionalCount: 2,
  },
  {
    id: 'sust_a',
    name: 'SUST A',
    title: 'SUST A ইউনিট প্রিসেট',
    durationMinutes: 50,
    totalQuestions: 60,
    mandatorySubjects: [
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 20 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 20 },
    ],
    optionalSubjects: [
      { subjectKey: 'math', name: 'উচ্চতর গণিত', count: 20 },
      { subjectKey: 'biology', name: 'জীববিজ্ঞান', count: 20 },
      { subjectKey: 'english', name: 'English', count: 20 },
    ],
    requiredOptionalCount: 1,
  },
  {
    id: 'du_kha',
    name: "ঢাবি 'খ'",
    title: "ঢাবি 'খ' প্রিসেট",
    durationMinutes: 45,
    totalQuestions: 60,
    mandatorySubjects: [
      { subjectKey: 'bangla', name: 'বাংলা', count: 20 },
      { subjectKey: 'english', name: 'English', count: 20 },
      { subjectKey: 'gk', name: 'সাধারণ জ্ঞান', count: 20 },
    ],
    optionalSubjects: [],
    requiredOptionalCount: 0,
  },
  {
    id: 'ju_a',
    name: 'জাবি এ',
    title: 'জাবি এ ইউনিট প্রিসেট',
    durationMinutes: 55,
    totalQuestions: 80,
    mandatorySubjects: [
      { subjectKey: 'math', name: 'উচ্চতর গণিত', count: 22 },
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 22 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 22 },
      { subjectKey: 'bangla', name: 'বাংলা', count: 7 },
      { subjectKey: 'english', name: 'English', count: 7 },
    ],
    optionalSubjects: [],
    requiredOptionalCount: 0,
  },
  {
    id: 'ju_d',
    name: 'জাবি ডি',
    title: 'জাবি ডি ইউনিট প্রিসেট',
    durationMinutes: 55,
    totalQuestions: 80,
    mandatorySubjects: [
      { subjectKey: 'biology', name: 'জীববিজ্ঞান', count: 44 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 24 },
      { subjectKey: 'bangla', name: 'বাংলা ও ইংরেজি', count: 8 },
      { subjectKey: 'gk', name: 'সাধারণ জ্ঞান', count: 4 },
    ],
    optionalSubjects: [],
    requiredOptionalCount: 0,
  },
  {
    id: 'medical',
    name: 'মেডিকেল',
    title: 'মেডিকেল (MBBS) প্রিসেট',
    durationMinutes: 60,
    totalQuestions: 100,
    mandatorySubjects: [
      { subjectKey: 'biology', name: 'জীববিজ্ঞান', count: 30 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 25 },
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 20 },
      { subjectKey: 'english', name: 'English', count: 15 },
      { subjectKey: 'gk', name: 'সাধারণ জ্ঞান', count: 10 },
    ],
    optionalSubjects: [],
    requiredOptionalCount: 0,
  },
  {
    id: 'buet',
    name: 'বুয়েট',
    title: 'বুয়েট প্রাক-নির্বাচনী প্রিসেট',
    durationMinutes: 60,
    totalQuestions: 100,
    mandatorySubjects: [
      { subjectKey: 'math', name: 'উচ্চতর গণিত', count: 34 },
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 33 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 33 },
    ],
    optionalSubjects: [],
    requiredOptionalCount: 0,
  },
  {
    id: 'cu_a',
    name: 'সিইউ এ',
    title: 'চট্টগ্রাম বিশ্ববিদ্যালয় এ ইউনিট',
    durationMinutes: 60,
    totalQuestions: 100,
    mandatorySubjects: [
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 25 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 25 },
    ],
    optionalSubjects: [
      { subjectKey: 'math', name: 'উচ্চতর গণিত', count: 25 },
      { subjectKey: 'biology', name: 'জীববিজ্ঞান', count: 25 },
      { subjectKey: 'english', name: 'English', count: 25 },
    ],
    requiredOptionalCount: 2,
  },
  {
    id: 'ruet',
    name: 'রুয়েট',
    title: 'ইঞ্জিনিয়ারিং গুচ্ছ প্রিসেট',
    durationMinutes: 60,
    totalQuestions: 100,
    mandatorySubjects: [
      { subjectKey: 'math', name: 'উচ্চতর গণিত', count: 35 },
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 35 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 30 },
    ],
    optionalSubjects: [],
    requiredOptionalCount: 0,
  },
];

export const SUBJECT_TOPICS_DATABASE: Record<string, PaperNode[]> = UNIFIED_SUBJECT_TOPICS_DATABASE;
